// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zifpgjbrldzfoohyiymv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppZnBnamJybGR6Zm9vaHlpeW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NzEyMjEsImV4cCI6MjA2MDE0NzIyMX0.mfbOZWS4YqMtpDy7zwiZGWf4qmW4_i9wmaibTwxJd_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);